language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
script: mvn package
after_success:
- travis/deploy.sh
env:
  global:
  - secure: dPZdGjaTeRdQTPS4UyDOCQh7QBDBbXmv5svJENXsSgvLBd0Cpmh4t1CQtOQYeCg648qUbDqKUewaDbvoHvl9zUTXgeDzYJXgwUWjUTLSdmZE/HvpBI8qjPOmtekfFP8VO/b3P9iTaUhkkmQWA2MyIPb4ZS8NQtTkSCdbVujy3viKEkmoXmiUXpPG/8N9oaSdOjJfWA7vdeBtdX9/hHoe8CMycYivop7OIsCNdCH0z0VEiG1r4Cz0Ny3ZYekZEwFa/MnCsuUqUeoU9E0AD8elxP26aDzt/MawQb9g1B4Ctl6kpXLJ65+YYHgZ90WIMbtWYh3D80TNh+AA6eq3pt7DHHTnKlGfYmtrqoP37lApmpIpS24JWJwbeSVQ8v8mx1K9ooCfNqZNJBgWYoiQ1AA2Wq80NUU2AAhaxOE9CinRAzwUzbJmKc3zCESOy1ervHtZl34yT/U7PyFokhFpBBFTHza/k4sqtcr7qAq9HLteVg0T9CXT7gKXncDrKQxd1jZWzI4DixIwbUGTfjmFWi+y7vRZ850Rjj3spgV6IqYXG65uzhIBMiYdYUxilgb797oUgh3pJutskqnTf1kiAKeplX+KfmWR0fUKAefatM/lEw9Mcpus+2sGf19AmlUnZLj0NvCWlCe02/xt1GOZyB1qj9HIuygFn/G+UWeawOHrUBU=
  - secure: QOfwtvqDj3b2rAgN+5f7QlzQJ/Yd669XSJyjkv/qJmJsjfveiU/uBqconFQSPp1WZzmv7D5yG5zMHtovqH0nrqfsSpwZoQJnw44imf9fkDUA6GWS4Z6OsPYQMWMTWZfCc4VepLAwOB4/ARdG9QF9XwgME3tHF/FwvcZTpyAyE66umgpFa/7DmbV32OcCporVq8W6l8K07j8VfxtYQjgZWFifWL38CC/WrYEaHmKt1UL7L9eycZZTbv31JgQX4gLQe/XYy33x4o+wawCO4T8r/RvxFnQgghZIvkCrhKEdkPDjixzZXJiXiwGvspVwox4NHVpf4iPgH6hKzqPCj3VCpSYhxXr/L8Kg7AfcuUWPjIwRiF3lQ/vOrui7Xa+EUFesIV4pERkwPXEa4ehSrOVWFxtWVh1fFluuP7XOPk37hqu7DVXIzRg7Ck1fdAZhdmwBnxsF1LxUZzQRZSFWUvoMxcVudkB/RurIXT0S/o0Ivk1NMovEpI9iUT508kwQUCWM9+U0lW8M10yI3Lr6OJ130AXEUe5qtlMrJQhe4TlD8uK/TtvL3wuWExM6hHIzAUAHXX8M9SWcs1S8Qio2JFjoOSKQGpvg7SMH9ZEgCiEJUJpDAnnsymOZaCX4FBg3tAHka1urFSNdIJuSGddfKe+XT7V2Z9ViFCpPeYo2MgpUaWY=
