//
// This file generated by rdl 1.4.14. Do not modify!
//

package com.yahoo.rdl;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Map;

//
// ArrayTypeDef - Array types can be restricted by item type and size
//
public class ArrayTypeDef {
    public String type;
    public String name;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String comment;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Map<String, String> annotations;
    public String items;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Integer size;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Integer minSize;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Integer maxSize;

    public ArrayTypeDef type(String type) {
        this.type = type;
        return this;
    }
    public ArrayTypeDef name(String name) {
        this.name = name;
        return this;
    }
    public ArrayTypeDef comment(String comment) {
        this.comment = comment;
        return this;
    }
    public ArrayTypeDef annotations(Map<String, String> annotations) {
        this.annotations = annotations;
        return this;
    }
    public ArrayTypeDef items(String items) {
        this.items = items;
        return this;
    }
    public ArrayTypeDef size(Integer size) {
        this.size = size;
        return this;
    }
    public ArrayTypeDef minSize(Integer minSize) {
        this.minSize = minSize;
        return this;
    }
    public ArrayTypeDef maxSize(Integer maxSize) {
        this.maxSize = maxSize;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != ArrayTypeDef.class) {
                return false;
            }
            ArrayTypeDef a = (ArrayTypeDef) another;
            if (type == null ? a.type != null : !type.equals(a.type)) {
                return false;
            }
            if (name == null ? a.name != null : !name.equals(a.name)) {
                return false;
            }
            if (comment == null ? a.comment != null : !comment.equals(a.comment)) {
                return false;
            }
            if (annotations == null ? a.annotations != null : !annotations.equals(a.annotations)) {
                return false;
            }
            if (items == null ? a.items != null : !items.equals(a.items)) {
                return false;
            }
            if (size == null ? a.size != null : !size.equals(a.size)) {
                return false;
            }
            if (minSize == null ? a.minSize != null : !minSize.equals(a.minSize)) {
                return false;
            }
            if (maxSize == null ? a.maxSize != null : !maxSize.equals(a.maxSize)) {
                return false;
            }
        }
        return true;
    }

    //
    // sets up the instance according to its default field values, if any
    //
    public ArrayTypeDef init() {
        if (items == null) {
            items = "Any";
        }
        return this;
    }
}
