//
// This file generated by rdl 1.4.6
//

package com.yahoo.rdl;

//
// BaseType -
//
public enum BaseType {
    Bool,
    Int8,
    Int16,
    Int32,
    Int64,
    Float32,
    Float64,
    Bytes,
    String,
    Timestamp,
    Symbol,
    UUID,
    Array,
    Map,
    Struct,
    Enum,
    Union,
    Any;

    public static BaseType fromString(String v) {
        for (BaseType e : values()) {
            if (e.toString().equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Invalid string representation for BaseType: " + v);
    }
}
