//
// This file generated by rdl 1.4.8
//

package com.yahoo.rdl;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

//
// EnumElementDef - EnumElementDef defines one of the elements of an Enum
//
@JsonSerialize(include = JsonSerialize.Inclusion.NON_DEFAULT)
public class EnumElementDef {
    public String symbol;
    @RdlOptional
    public String comment;

    public EnumElementDef symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    public EnumElementDef comment(String comment) {
        this.comment = comment;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != EnumElementDef.class) {
                return false;
            }
            EnumElementDef a = (EnumElementDef) another;
            if (symbol == null ? a.symbol != null : !symbol.equals(a.symbol)) {
                return false;
            }
            if (comment == null ? a.comment != null : !comment.equals(a.comment)) {
                return false;
            }
        }
        return true;
    }
}
