//
// This file generated by rdl 1.4.14. Do not modify!
//

package com.yahoo.rdl;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Map;

//
// EnumElementDef - EnumElementDef defines one of the elements of an Enum
//
public class EnumElementDef {
    public String symbol;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String comment;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Map<String, String> annotations;

    public EnumElementDef symbol(String symbol) {
        this.symbol = symbol;
        return this;
    }
    public EnumElementDef comment(String comment) {
        this.comment = comment;
        return this;
    }
    public EnumElementDef annotations(Map<String, String> annotations) {
        this.annotations = annotations;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != EnumElementDef.class) {
                return false;
            }
            EnumElementDef a = (EnumElementDef) another;
            if (symbol == null ? a.symbol != null : !symbol.equals(a.symbol)) {
                return false;
            }
            if (comment == null ? a.comment != null : !comment.equals(a.comment)) {
                return false;
            }
            if (annotations == null ? a.annotations != null : !annotations.equals(a.annotations)) {
                return false;
            }
        }
        return true;
    }
}
