//
// This file generated by rdl 1.5.1. Do not modify!
//

package com.yahoo.rdl;
import com.fasterxml.jackson.annotation.JsonInclude;

//
// ExceptionDef - ExceptionDef describes the exception a symbolic response code
// maps to.
//
public class ExceptionDef {
    public String type;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String comment;

    public ExceptionDef type(String type) {
        this.type = type;
        return this;
    }
    public ExceptionDef comment(String comment) {
        this.comment = comment;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != ExceptionDef.class) {
                return false;
            }
            ExceptionDef a = (ExceptionDef) another;
            if (type == null ? a.type != null : !type.equals(a.type)) {
                return false;
            }
            if (comment == null ? a.comment != null : !comment.equals(a.comment)) {
                return false;
            }
        }
        return true;
    }
}
