//
// This file generated by rdl 1.4.14. Do not modify!
//

package com.yahoo.rdl;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Map;

//
// ResourceOutput - ResourceOutput defines output characteristics of a Resource
//
public class ResourceOutput {
    public String name;
    public String type;
    public String header;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String comment;
    public boolean optional;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Map<String, String> annotations;

    public ResourceOutput name(String name) {
        this.name = name;
        return this;
    }
    public ResourceOutput type(String type) {
        this.type = type;
        return this;
    }
    public ResourceOutput header(String header) {
        this.header = header;
        return this;
    }
    public ResourceOutput comment(String comment) {
        this.comment = comment;
        return this;
    }
    public ResourceOutput optional(boolean optional) {
        this.optional = optional;
        return this;
    }
    public ResourceOutput annotations(Map<String, String> annotations) {
        this.annotations = annotations;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != ResourceOutput.class) {
                return false;
            }
            ResourceOutput a = (ResourceOutput) another;
            if (name == null ? a.name != null : !name.equals(a.name)) {
                return false;
            }
            if (type == null ? a.type != null : !type.equals(a.type)) {
                return false;
            }
            if (header == null ? a.header != null : !header.equals(a.header)) {
                return false;
            }
            if (comment == null ? a.comment != null : !comment.equals(a.comment)) {
                return false;
            }
            if (optional != a.optional) {
                return false;
            }
            if (annotations == null ? a.annotations != null : !annotations.equals(a.annotations)) {
                return false;
            }
        }
        return true;
    }
}
