//
// This file generated by rdl 1.4.14. Do not modify!
//

package com.yahoo.rdl;
import com.fasterxml.jackson.annotation.JsonInclude;

//
// ResourceAuth - ResourceAuth defines authentication and authorization
// attributes of a resource. Presence of action, resource, or domain implies
// authentication; the authentication flag alone is required only when no
// authorization is done.
//
public class ResourceAuth {
    public boolean authenticate;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String action;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String resource;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String domain;

    public ResourceAuth authenticate(boolean authenticate) {
        this.authenticate = authenticate;
        return this;
    }
    public ResourceAuth action(String action) {
        this.action = action;
        return this;
    }
    public ResourceAuth resource(String resource) {
        this.resource = resource;
        return this;
    }
    public ResourceAuth domain(String domain) {
        this.domain = domain;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != ResourceAuth.class) {
                return false;
            }
            ResourceAuth a = (ResourceAuth) another;
            if (authenticate != a.authenticate) {
                return false;
            }
            if (action == null ? a.action != null : !action.equals(a.action)) {
                return false;
            }
            if (resource == null ? a.resource != null : !resource.equals(a.resource)) {
                return false;
            }
            if (domain == null ? a.domain != null : !domain.equals(a.domain)) {
                return false;
            }
        }
        return true;
    }
}
