//
// This file generated by rdl 1.4.6
//

package com.yahoo.rdl;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

//
// ResourceOutput - ResourceOutput defines output characteristics of a Resource
//
@JsonSerialize(include = JsonSerialize.Inclusion.NON_DEFAULT)
public class ResourceOutput {
    public String name;
    public String type;
    public String header;
    @RdlOptional
    public String comment;
    public boolean optional;

    public ResourceOutput name(String name) {
        this.name = name;
        return this;
    }
    public ResourceOutput type(String type) {
        this.type = type;
        return this;
    }
    public ResourceOutput header(String header) {
        this.header = header;
        return this;
    }
    public ResourceOutput comment(String comment) {
        this.comment = comment;
        return this;
    }
    public ResourceOutput optional(boolean optional) {
        this.optional = optional;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != ResourceOutput.class) {
                return false;
            }
            ResourceOutput a = (ResourceOutput) another;
            if (name == null ? a.name != null : !name.equals(a.name)) {
                return false;
            }
            if (type == null ? a.type != null : !type.equals(a.type)) {
                return false;
            }
            if (header == null ? a.header != null : !header.equals(a.header)) {
                return false;
            }
            if (comment == null ? a.comment != null : !comment.equals(a.comment)) {
                return false;
            }
            if (optional != a.optional) {
                return false;
            }
        }
        return true;
    }
}
