//
// This file generated by rdl 1.5.1. Do not modify!
//

package com.yahoo.rdl;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Map;

//
// StructFieldDef - Each field in a struct_field_spec is defined by this type
//
public class StructFieldDef {
    public String name;
    public String type;
    public boolean optional;
    @com.fasterxml.jackson.annotation.JsonProperty("default")
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Object _default;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String comment;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String items;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String keys;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Map<String, String> annotations;

    public StructFieldDef name(String name) {
        this.name = name;
        return this;
    }
    public StructFieldDef type(String type) {
        this.type = type;
        return this;
    }
    public StructFieldDef optional(boolean optional) {
        this.optional = optional;
        return this;
    }
    public StructFieldDef _default(Object _default) {
        this._default = _default;
        return this;
    }
    public StructFieldDef comment(String comment) {
        this.comment = comment;
        return this;
    }
    public StructFieldDef items(String items) {
        this.items = items;
        return this;
    }
    public StructFieldDef keys(String keys) {
        this.keys = keys;
        return this;
    }
    public StructFieldDef annotations(Map<String, String> annotations) {
        this.annotations = annotations;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != StructFieldDef.class) {
                return false;
            }
            StructFieldDef a = (StructFieldDef) another;
            if (name == null ? a.name != null : !name.equals(a.name)) {
                return false;
            }
            if (type == null ? a.type != null : !type.equals(a.type)) {
                return false;
            }
            if (optional != a.optional) {
                return false;
            }
            if (_default == null ? a._default != null : !_default.equals(a._default)) {
                return false;
            }
            if (comment == null ? a.comment != null : !comment.equals(a.comment)) {
                return false;
            }
            if (items == null ? a.items != null : !items.equals(a.items)) {
                return false;
            }
            if (keys == null ? a.keys != null : !keys.equals(a.keys)) {
                return false;
            }
            if (annotations == null ? a.annotations != null : !annotations.equals(a.annotations)) {
                return false;
            }
        }
        return true;
    }
}
