//
// This file generated by rdl 1.5.1. Do not modify!
//

package com.yahoo.rdl;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;
import java.util.Map;

//
// UnionTypeDef - Define a type as one of any other specified type.
//
public class UnionTypeDef {
    public String type;
    public String name;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String comment;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Map<String, String> annotations;
    public List<String> variants;

    public UnionTypeDef type(String type) {
        this.type = type;
        return this;
    }
    public UnionTypeDef name(String name) {
        this.name = name;
        return this;
    }
    public UnionTypeDef comment(String comment) {
        this.comment = comment;
        return this;
    }
    public UnionTypeDef annotations(Map<String, String> annotations) {
        this.annotations = annotations;
        return this;
    }
    public UnionTypeDef variants(List<String> variants) {
        this.variants = variants;
        return this;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != UnionTypeDef.class) {
                return false;
            }
            UnionTypeDef a = (UnionTypeDef) another;
            if (type == null ? a.type != null : !type.equals(a.type)) {
                return false;
            }
            if (name == null ? a.name != null : !name.equals(a.name)) {
                return false;
            }
            if (comment == null ? a.comment != null : !comment.equals(a.comment)) {
                return false;
            }
            if (annotations == null ? a.annotations != null : !annotations.equals(a.annotations)) {
                return false;
            }
            if (variants == null ? a.variants != null : !variants.equals(a.variants)) {
                return false;
            }
        }
        return true;
    }
}
