//
// This file generated by rdl 1.3.10
//

import java.util.List;
import java.util.Map;
import com.yahoo.rdl.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

//
// Point -
//
@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public final class Point {
    public int x;
    public int y;

    public Point x(int x) { this.x = x; return this; }
    public Point y(int y) { this.y = y; return this; }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != Point.class) {
                return false;
            }
            Point a = (Point) another;
            if (x != a.x) {
                return false;
            }
            if (y != a.y) {
                return false;
            }
        }
        return true;
    }
}
