//
// This file generated by rdl 1.3.5
//

import com.yahoo.rdl.*;

public class TestSchema {

    private final static Schema _instance = build();
    public static Schema instance() { return _instance; }

    private static Schema build() {
        SchemaBuilder sb = new SchemaBuilder("test");

        sb.structType("Point")
            .field("x", "Int32", false, "")
            .field("y", "Int32", false, "");

        sb.structType("Polyline")
            .arrayField("points", "Point", false, "");



        return sb.build();
    }

}
